[TMP]: Add missing FCM entry The following HALs in device manifest are not declared in FCM <= level 3:   android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default (@2)   android.hardware.drm.IDrmFactory/clearkey (@1)   android.hardware.power.IPower/default (@3)   android.hardware.radio.config@1.1::IRadioConfig/default   android.hardware.wifi.hostapd.IHostapd/default (@1)   android.hardware.wifi.supplicant.ISupplicant/default (@1)
ERROR: files are incompatible: Device manifest and framework compatibility matrix are incompatible: HALs incompatible. Matrix level = 3. Manifest level = 3. The following requirements are not met:
android.hardware.audio:
    required:
        @7.0-1::IDevicesFactory/default OR
        @5.0::IDevicesFactory/default OR
        @6.0::IDevicesFactory/default
    provided:
android.hardware.audio:
    required:
        @4.0::IDevicesFactory/default OR
        @5.0::IDevicesFactory/default OR
        @6.0::IDevicesFactory/default OR
        @7.0-1::IDevicesFactory/default
    provided:
android.hardware.audio.effect:
    required:
        @7.0::IEffectsFactory/default OR
        @5.0::IEffectsFactory/default OR
        @6.0::IEffectsFactory/default
    provided:
android.hardware.audio.effect:
    required:
        @4.0::IEffectsFactory/default OR
        @5.0::IEffectsFactory/default OR
        @6.0::IEffectsFactory/default OR
        @7.0::IEffectsFactory/default
    provided: